version: '3'
services:
  deutsche-bahn-saver-hamburg-hbf:
    build: ./
    command:
      - "--eva=8002549"
    links:
      - "mongo:mongoservice"
      - "deutsche-bahn-data-acquisition:db-data-acquisition"

  deutsche-bahn-saver-berlin-hbf:
    build: ./
    command:
      - "--eva=8011160"
    links:
      - "mongo:mongoservice"
      - "deutsche-bahn-data-acquisition:db-data-acquisition"

  mongo:
    image: mongo:4.0.4
    ports:
      - 27017:27017
    
    volumes:
      - /home/jonas/mongodb/database:/data/db

  deutsche-bahn-data-acquisition:
    build: https://github.com/jonasbarth/deutsche-bahn-data.git#main
    image: jonas/deutsche-bahn-data-acquisition
    ports:
      - 5000:5000
      - 5001:5001

  deutsche-bahn-station:
    build: https://github.com/jonasbarth/deutsche-bahn-station.git#main
    ports:
      - 6000:6000
    links:
      - "mongo:mongoservice"