version: '3'
services:
  deutsche-bahn-saver:
    build: ./
    image: jonas/deutsche-bahn-saver
    command:
      - "8002549"
    links:
      - "mongo:mongoservice"

  mongo:
    image: mongo:4.0.4
    ports:
      - 27017:27017
    
    volumes:
      - /home/jonas/mongodb/database:/data/db