version: '3'
services:
  deutsche-bahn-saver:
    build: ./
    image: jonas/deutsche-bahn-saver
    command:
      - "8002549"
    links:
      - "mongo:mongoservice"
      - "deutsche-bahn-data-acquisition:db-data-acquisition"

  mongo:
    image: mongo:4.0.4
    ports:
      - 27017:27017
    
    volumes:
      - /home/jonas/mongodb/database:/data/db

  deutsche-bahn-data-acquisition:
    build: https://github.com/jonasbarth/deutsche-bahn-data/blob/main/Dockerfile
    image: jonas/deutsche-bahn-data-acquisition
    ports:
      - 5000:5000
      - 5001:5001